#!/usr/bin/env bash
set -euo pipefail

repo=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)
helper=$repo/scripts/dwm-xsettings
work=$(mktemp -d)
runtime=$work/runtime
home=$work/home
config_home=$home/.config
config_file=$config_home/dwm-titus/xsettingsd.conf
bin_dir=$work/bin
log_file=$work/xsettingsd.log
declare -a fixture_pids=()

cleanup() {
	local pid
	for pid in "${fixture_pids[@]}"; do
		kill -TERM "$pid" 2>/dev/null || true
	done
	find "$work" -depth -delete
}
trap cleanup EXIT HUP INT TERM

mkdir -p "$runtime" "${config_file%/*}" "$bin_dir"
chmod 700 "$runtime"

cat >"$work/xsettingsd-fixture.c" <<'EOF'
#include <ctype.h>
#include <signal.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>

static volatile sig_atomic_t reloaded;
static volatile sig_atomic_t running = 1;
static const char *config_path;
static char state_path[4096];

static void handle_hup(int signal_number) {
	(void)signal_number;
	signal(SIGHUP, handle_hup);
	reloaded = 1;
}

static void handle_term(int signal_number) {
	(void)signal_number;
	running = 0;
}

static void record(const char *event) {
	const char *path = getenv("DWM_TEST_XSETTINGSD_LOG");
	FILE *stream;
	if (!path || !(stream = fopen(path, "a")))
		_exit(2);
	fprintf(stream, "%s\t%ld\t%s\n", event, (long)getpid(),
	        getenv("DISPLAY") ? getenv("DISPLAY") : "");
	fclose(stream);
}

static int publish_config(void) {
	char line[4096];
	char dpi[32] = "";
	int first = 1;
	FILE *config = fopen(config_path, "r");
	FILE *state;
	if (!config)
		return 0;
	while (fgets(line, sizeof(line), config)) {
		line[strcspn(line, "\r\n")] = '\0';
		if (first) {
			if (strcmp(line, "# Auto-generated by theme-apply.sh - do not edit manually.")) {
				fclose(config);
				return 0;
			}
			first = 0;
		} else if (!line[0] || line[0] == '#' || !strcmp(line, "Keep/Setting \"yes\"")) {
			continue;
		} else if (sscanf(line, "Xft/DPI %31[0-9]", dpi) == 1) {
			continue;
		} else {
			fclose(config);
			return 0;
		}
	}
	fclose(config);
	if (!dpi[0] || !(state = fopen(state_path, "w")))
		return 0;
	fprintf(state, "%s\n", dpi);
	fclose(state);
	return 1;
}

static void make_state_path(void) {
	const char *prefix = getenv("DWM_TEST_XSETTINGS_STATE_PREFIX");
	const char *display = getenv("DISPLAY");
	size_t length;
	if (!prefix || !display)
		_exit(2);
	length = snprintf(state_path, sizeof(state_path), "%s.", prefix);
	while (*display && length + 1 < sizeof(state_path)) {
		state_path[length++] = isalnum((unsigned char)*display) || *display == '.' ||
			*display == '_' || *display == '-' ? *display : '_';
		display++;
	}
	state_path[length] = '\0';
}

int main(int argc, char **argv) {
	if (argc == 3 && (!strcmp(argv[1], "-c") || !strcmp(argv[1], "--config")))
		config_path = argv[2];
	else if (argc == 2 && !strncmp(argv[1], "--config=", 9))
		config_path = argv[1] + 9;
	else
		return 2;
	make_state_path();
	if (!publish_config())
		return 1;
	fprintf(stderr, "xsettingsd: Loaded fixture from %s\n", config_path);
	fflush(stderr);
	signal(SIGHUP, handle_hup);
	signal(SIGTERM, handle_term);
	record("start");
	while (running) {
		pause();
		if (reloaded) {
			reloaded = 0;
			fprintf(stderr, "xsettingsd: Reloading configuration\n");
			if (publish_config())
				fprintf(stderr, "xsettingsd: Loaded fixture from %s\n", config_path);
			else
				fprintf(stderr, "xsettingsd: Unable to parse %s: rejected fixture setting\n",
				        config_path);
			fflush(stderr);
			record("reload");
		}
	}
	unlink(state_path);
	record("stop");
	return 0;
}
EOF
${CC:-cc} -std=c99 -Wall -Wextra -Werror -o "$bin_dir/xsettingsd" \
	"$work/xsettingsd-fixture.c"

cat >"$bin_dir/dump_xsettings" <<'SH'
#!/bin/sh
set -eu
[ "${DWM_TEST_DUMP_HANG:-0}" != 1 ] || exec sleep 30
suffix=$(printf '%s' "${DISPLAY:?}" | sed 's/[^A-Za-z0-9._-]/_/g')
if [ -n "${DWM_TEST_DUMP_DISPLAY_OVERRIDE:-}" ]; then
	suffix=$(printf '%s' "$DWM_TEST_DUMP_DISPLAY_OVERRIDE" | sed 's/[^A-Za-z0-9._-]/_/g')
fi
state=${DWM_TEST_XSETTINGS_STATE_PREFIX:?}.$suffix
[ -s "$state" ] || exit 1
printf 'Xft/DPI %s\n' "$(cat "$state")"
SH
chmod +x "$bin_dir/dump_xsettings"

run_helper() {
	run_helper_for_display :77 "$@"
}

run_helper_for_display() {
	local display=$1
	shift
	DISPLAY=$display DWM_TEST_XSETTINGSD_LOG=$log_file \
		DWM_TEST_XSETTINGS_STATE_PREFIX=$work/published HOME=$home \
		XDG_CONFIG_HOME=$config_home XDG_RUNTIME_DIR=$runtime \
		PATH="$bin_dir:/usr/bin:/bin" "$helper" "$@"
}

wait_for_log() {
	local pattern=$1 attempt
	for ((attempt = 0; attempt < 100; attempt++)); do
		grep -Eq "$pattern" "$log_file" 2>/dev/null && return 0
		sleep 0.02
	done
	return 1
}

fixture_process_running() {
	state=$(awk '{ line = $0; sub(/^.*\) /, "", line); split(line, fields, " "); print fields[1] }' \
		"/proc/$1/stat" 2>/dev/null || true)
	[ -n "$state" ] && [ "$state" != Z ]
}

printf '# Auto-generated by theme-apply.sh - do not edit manually.\nXft/DPI 122880\n' \
	>"$config_file"
integration_lock=$runtime/dwm-theme-apply.lock
exec 8>"$integration_lock"
flock 8
run_helper session-apply | grep -Fqx $'result\tactive\t122880'
wait_for_log $'^start\t[0-9]+\t:77$'
managed_pid=$(awk -F '\t' '$1 == "start" && $3 == ":77" { print $2; exit }' "$log_file")
fixture_pids+=("$managed_pid")
kill -0 "$managed_pid"
exec 8>&-
if ! flock -n "$integration_lock" -c true; then
	printf 'managed xsettingsd inherited the theme integration lock\n' >&2
	exit 1
fi

cp -- "$bin_dir/xsettingsd" "$work/xsettingsd.replacement"
mv -- "$work/xsettingsd.replacement" "$bin_dir/xsettingsd"
case $(readlink -- "/proc/$managed_pid/exe") in
*'xsettingsd (deleted)') ;;
*)
	printf 'fixture did not create an upgraded deleted-inode process\n' >&2
	exit 1
	;;
esac

printf '# Auto-generated by theme-apply.sh - do not edit manually.\nKeep/Setting "yes"\nXft/DPI 147456\n' \
	>"$config_file"
run_helper reload | grep -Fqx $'result\tactive\t147456'
wait_for_log $'^reload\t[0-9]+\t:77$'
run_helper status | grep -Fqx $'state\tactive\t147456'
DISPLAY=:77.0 DWM_TEST_DUMP_DISPLAY_OVERRIDE=:77 \
	run_helper_for_display :77.0 status | grep -Fqx $'state\tactive\t147456'
DWM_TEST_DUMP_DISPLAY_OVERRIDE=:77 \
	run_helper_for_display unix:77 reload | grep -Fqx $'result\tactive\t147456'
if [[ $(awk -F '\t' '$1 == "start" && $3 == ":77" { count++ } END { print count + 0 }' \
	"$log_file") -ne 1 ]]; then
	printf 'reload started a competing daemon after an executable upgrade\n' >&2
	exit 1
fi
grep -Fqx 'Keep/Setting "yes"' "$config_file"

printf '# Auto-generated by theme-apply.sh - do not edit manually.\nRejected setting\nXft/DPI 172032\n' \
	>"$config_file"
if run_helper reload >"$work/rejected-reload.out" 2>"$work/rejected-reload.err"; then
	printf 'rejected xsettingsd reload was reported successful\n' >&2
	exit 1
fi
grep -Fq 'rejected the requested configuration reload' "$work/rejected-reload.err"
grep -Fqx 147456 "$work/published._77"
printf '# Auto-generated by theme-apply.sh - do not edit manually.\nRejected setting\nXft/DPI 147456\n' \
	>"$config_file"
if run_helper reload >"$work/rejected-same-dpi.out" 2>"$work/rejected-same-dpi.err"; then
	printf 'rejected same-DPI xsettingsd reload was reported successful\n' >&2
	exit 1
fi
grep -Fq 'rejected the requested configuration reload' "$work/rejected-same-dpi.err"
grep -Fqx 147456 "$work/published._77"
printf '# Auto-generated by theme-apply.sh - do not edit manually.\nKeep/Setting "yes"\nXft/DPI 147456\n' \
	>"$config_file"

close_watch_ready=$work/close-watch.ready
DISPLAY=:77 DWM_TEST_XSETTINGSD_LOG=$log_file \
	DWM_TEST_XSETTINGS_STATE_PREFIX=$work/published \
	DWM_TEST_XSETTINGS_WATCH_READY=$close_watch_ready HOME=$home \
	XDG_CONFIG_HOME=$config_home XDG_RUNTIME_DIR=$runtime \
	PATH="$bin_dir:/usr/bin:/bin" "$helper" watch \
	>"$work/close-watch.out" 2>"$work/close-watch.err" &
close_watch_pid=$!
for _ in {1..100}; do
	[[ -e $close_watch_ready ]] && break
	sleep 0.02
done
if [[ ! -e $close_watch_ready ]]; then
	printf 'close-path XSETTINGS owner watch did not become ready\n' >&2
	cat "$work/close-watch.err" >&2
	exit 1
fi
close_wait_pid=
for _ in {1..100}; do
	close_wait_pid=$(pgrep -P "$close_watch_pid" -x pidwait 2>/dev/null || true)
	[[ -n $close_wait_pid ]] && break
	sleep 0.02
done
if [[ -z $close_wait_pid ]]; then
	printf 'close-path XSETTINGS owner watch did not start pidwait\n' >&2
	exit 1
fi
kill -TERM "$close_watch_pid"
if wait "$close_watch_pid"; then
	printf 'terminated XSETTINGS owner watch reported an event\n' >&2
	exit 1
fi
for _ in {1..100}; do
	kill -0 "$close_wait_pid" 2>/dev/null || break
	sleep 0.02
done
if kill -0 "$close_wait_pid" 2>/dev/null; then
	printf 'terminated XSETTINGS owner watch left pidwait running\n' >&2
	exit 1
fi
fixture_process_running "$managed_pid"

owner_watch_ready=$work/owner-watch.ready
DWM_TEST_XSETTINGS_WATCH_READY=$owner_watch_ready \
	run_helper watch >"$work/owner-watch.out" 2>"$work/owner-watch.err" &
owner_watch_pid=$!
for _ in {1..100}; do
	[[ -e $owner_watch_ready ]] && break
	sleep 0.02
done
if [[ ! -e $owner_watch_ready ]]; then
	printf 'XSETTINGS owner watch did not become ready\n' >&2
	cat "$work/owner-watch.err" >&2
	exit 1
fi
kill -0 "$owner_watch_pid"
kill -TERM "$managed_pid"
if ! wait "$owner_watch_pid"; then
	printf 'XSETTINGS owner watch did not report the managed daemon exit\n' >&2
	cat "$work/owner-watch.err" >&2
	exit 1
fi
grep -Fqx $'xsettings-event-protocol\t1\t0' "$work/owner-watch.out"
grep -Fqx changed "$work/owner-watch.out"
for _ in {1..100}; do
	fixture_process_running "$managed_pid" || break
	sleep 0.02
done
run_helper status | grep -Fqx $'state\tinactive\t147456'
run_helper session-apply | grep -Fqx $'result\tactive\t147456'
for _ in {1..100}; do
	managed_pid=$(awk -F '\t' '$1 == "start" && $3 == ":77" { pid = $2 } END { print pid }' \
		"$log_file")
	[[ -n $managed_pid ]] && fixture_process_running "$managed_pid" && break
	sleep 0.02
done
fixture_pids+=("$managed_pid")
fixture_process_running "$managed_pid"

printf '# Auto-generated by theme-apply.sh - do not edit manually.\nXft/DPI 172032\n' \
	>"$config_file"
set +e
DWM_TEST_DUMP_HANG=1 run_helper reload >"$work/hanging-dump.out" \
	2>"$work/hanging-dump.err"
hanging_dump_status=$?
set -e
[[ $hanging_dump_status -ne 0 && $hanging_dump_status -ne 124 ]]
grep -Fq 'did not publish the requested X11 text scale' "$work/hanging-dump.err"
printf '# Auto-generated by theme-apply.sh - do not edit manually.\nKeep/Setting "yes"\nXft/DPI 147456\n' \
	>"$config_file"
run_helper reload | grep -Fqx $'result\tactive\t147456'

DISPLAY=:78 DWM_TEST_XSETTINGSD_LOG=$log_file \
	DWM_TEST_XSETTINGS_STATE_PREFIX=$work/published \
	"$bin_dir/xsettingsd" --config "$config_file" &
other_pid=$!
fixture_pids+=("$other_pid")
wait_for_log $'^start\t[0-9]+\t:78$'

printf '# Auto-generated by theme-apply.sh - do not edit manually.\nKeep/Setting "yes"\n' \
	>"$config_file"
run_helper status | grep -Fqx $'state\tstale\t147456'
if env -u DISPLAY HOME="$home" XDG_CONFIG_HOME="$config_home" XDG_RUNTIME_DIR="$runtime" \
	PATH="$bin_dir:/usr/bin:/bin" "$helper" session-apply \
	>"$work/no-display-reset.out" 2>"$work/no-display-reset.err"; then
	printf 'system-follow reset without DISPLAY was reported successful\n' >&2
	exit 1
fi
grep -Fq 'DISPLAY is required to restore system X11 text scaling' \
	"$work/no-display-reset.err"
fixture_process_running "$managed_pid"
stale_watch_ready=$work/stale-watch.ready
DWM_TEST_XSETTINGS_WATCH_READY=$stale_watch_ready \
	run_helper watch >"$work/stale-watch.out" 2>"$work/stale-watch.err" &
stale_watch_pid=$!
for _ in {1..100}; do
	[[ -e $stale_watch_ready ]] && break
	sleep 0.02
done
if [[ ! -e $stale_watch_ready ]]; then
	printf 'stale XSETTINGS owner watch did not become ready\n' >&2
	cat "$work/stale-watch.err" >&2
	exit 1
fi
kill -0 "$stale_watch_pid"
run_helper session-apply | grep -Fqx $'result\tsystem-follow'
if ! wait "$stale_watch_pid"; then
	printf 'stale XSETTINGS owner watch did not report owner loss\n' >&2
	cat "$work/stale-watch.err" >&2
	exit 1
fi
grep -Fqx $'xsettings-event-protocol\t1\t0' "$work/stale-watch.out"
grep -Fqx 'changed' "$work/stale-watch.out"
for _ in {1..100}; do
	fixture_process_running "$managed_pid" || break
	sleep 0.02
done
if fixture_process_running "$managed_pid"; then
	printf 'managed xsettingsd did not stop on system-follow reset\n' >&2
	exit 1
fi
run_helper status | grep -Fqx $'state\tsystem-follow'
kill -0 "$other_pid"

printf '# Auto-generated by theme-apply.sh - do not edit manually.\nXft/DPI 100000\n' \
	>"$work/external.conf"
DISPLAY=:77 DWM_TEST_XSETTINGSD_LOG=$log_file \
	DWM_TEST_XSETTINGS_STATE_PREFIX=$work/published \
	"$bin_dir/xsettingsd" --config "$work/external.conf" &
external_pid=$!
fixture_pids+=("$external_pid")
wait_for_log $'^start\t[0-9]+\t:77$'
printf '# Auto-generated by theme-apply.sh - do not edit manually.\nXft/DPI 122880\n' \
	>"$config_file"
if run_helper reload >"$work/external-owner.out" 2>"$work/external-owner.err"; then
	printf 'existing XSETTINGS owner was replaced\n' >&2
	exit 1
fi
grep -Fq 'another XSETTINGS manager already owns this display' "$work/external-owner.err"
kill -0 "$external_pid"
grep -Fqx 100000 "$work/published._77"

printf '# Auto-generated by theme-apply.sh - do not edit manually.\nXft/DPI 122880\nXft/DPI 147456\n' \
	>"$config_file"
if run_helper status >"$work/duplicate.out" 2>"$work/duplicate.err"; then
	printf 'duplicate Xft/DPI configuration was accepted\n' >&2
	exit 1
fi
grep -Fq 'duplicate Xft/DPI setting' "$work/duplicate.err"

printf '# Auto-generated by theme-apply.sh - do not edit manually.\nXft/DPI 122880\n' \
	>"$config_file"
mv "$bin_dir/xsettingsd" "$bin_dir/xsettingsd.unavailable"
DWM_TEST_XSETTINGSD_UNAVAILABLE=1 run_helper status |
	grep -Fqx $'state\tunavailable\t122880'
if DWM_TEST_XSETTINGSD_UNAVAILABLE=1 run_helper reload \
	>"$work/unavailable.out" 2>"$work/unavailable.err"; then
	printf 'missing xsettingsd backend was accepted\n' >&2
	exit 1
fi
grep -Fq 'xsettingsd is unavailable' "$work/unavailable.err"

mv "$bin_dir/xsettingsd.unavailable" "$bin_dir/xsettingsd"
mv "$bin_dir/dump_xsettings" "$bin_dir/dump_xsettings.unavailable"
DWM_TEST_DUMP_XSETTINGS_UNAVAILABLE=1 run_helper status |
	grep -Fqx $'state\tunavailable\t122880'
if DWM_TEST_DUMP_XSETTINGS_UNAVAILABLE=1 run_helper reload \
	>"$work/no-dump.out" 2>"$work/no-dump.err"; then
	printf 'missing live XSETTINGS verifier was accepted\n' >&2
	exit 1
fi
grep -Fq 'dump_xsettings is unavailable' "$work/no-dump.err"

printf 'dwm XSETTINGS lifecycle tests: PASS\n'
