#!/bin/sh
# dwm-titus autostart — single unified autostart script
# Phase 1: Blocking setup (must complete before windows appear)
# Phase 2: Background services (compositor, notifications, shell, tray apps)

start_once() {
	process_name=$1
	shift

	command -v "$1" >/dev/null 2>&1 || return 0
	pgrep -u "$(id -u)" -x "$process_name" >/dev/null 2>&1 && return 0
	"$@" >/dev/null 2>&1 &
}

start_detached_once() {
	process_name=$1
	shift

	command -v "$1" >/dev/null 2>&1 || return 0
	pgrep -u "$(id -u)" -x "$process_name" >/dev/null 2>&1 && return 0
	if [ "${DWM_AUTOSTART_NO_SETSID:-0}" != 1 ] &&
		command -v setsid >/dev/null 2>&1; then
		setsid -f "$@" >/dev/null 2>&1
	else
		"$@" >/dev/null 2>&1 &
	fi
}

PICOM_BACKEND=${PICOM_BACKEND:-xrender}

# ── Phase 1: Blocking ──────────────────────────────────────────────────────────
# Disable DPMS and screen blanking (prevents GPU/display wake issues)
if command -v xset >/dev/null 2>&1; then
	xset s off
	xset s noblank
	xset -dpms
fi

# Export display env to systemd/dbus in parallel (both are IPC round-trips)
if command -v systemctl >/dev/null 2>&1; then
	systemctl --user import-environment DISPLAY XAUTHORITY &
fi
dbus-update-activation-environment --systemd DISPLAY XAUTHORITY 2>/dev/null &
wait

# ── Phase 2: Background services ───────────────────────────────────────────────

# Source theme environment so tray apps (e.g. flameshot) inherit QT_QPA_PLATFORMTHEME
# This file is generated by theme-apply.sh and updated on every theme change.
THEME_ENV="${XDG_CONFIG_HOME:-$HOME/.config}/dwm-titus/theme-env.sh"
# shellcheck disable=SC1090
[ -f "$THEME_ENV" ] && . "$THEME_ENV"

# Wallpaper (moved here from Phase 1 — does not need to block dwm startup)
if command -v feh >/dev/null 2>&1 &&
	find "$HOME/Pictures/backgrounds" -type f -print -quit 2>/dev/null |
	grep -q .; then
	start_once feh feh --randomize --bg-fill "$HOME/Pictures/backgrounds"
fi

# Compositor
start_detached_once picom picom --backend "$PICOM_BACKEND"

# dwm root-window status publisher for Quickshell's event-driven panel.
start_detached_once dwm-status dwm-status

# Session locker for the power menu lock action and loginctl lock requests.
start_once light-locker light-locker

# Quickshell is the managed shell for this session. Dunst remains the fallback
# notification daemon when the managed Quickshell config is unavailable.
QUICKSHELL_CONFIG="${XDG_CONFIG_HOME:-$HOME/.config}/quickshell/shell.qml"
if [ -f "$QUICKSHELL_CONFIG" ]; then
	start_detached_once quickshell quickshell --no-duplicate
else
	start_once dunst dunst
fi

# Polkit authentication agent (try common agents)
for agent in \
	/usr/lib/mate-polkit/polkit-mate-authentication-agent-1 \
	/usr/libexec/polkit-mate-authentication-agent-1 \
	/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 \
	/usr/libexec/polkit-gnome-authentication-agent-1 \
	/usr/lib/polkit-kde-authentication-agent-1 \
	/usr/libexec/polkit-kde-authentication-agent-1 \
	/usr/bin/lxpolkit \
	/usr/lib/lxpolkit/lxpolkit; do
	if [ -x "$agent" ]; then
		agent_name=$(basename "$agent")
		if ! pgrep -u "$(id -u)" -x "$agent_name" >/dev/null 2>&1; then
			"$agent" >/dev/null 2>&1 &
		fi
		break
	fi
done

if command -v dex >/dev/null 2>&1; then
	dex -a 2>/dev/null
elif command -v dex-autostart >/dev/null 2>&1; then
	dex-autostart -a 2>/dev/null
fi
