#!/bin/sh
# dwm-titus autostart — single unified autostart script
# Phase 1: Blocking setup (must complete before windows appear)
# Phase 2: Background services (compositor, notifications, polybar, tray apps)

# ── Phase 1: Blocking ──────────────────────────────────────────────────────────
# Disable DPMS and screen blanking (prevents GPU/display wake issues)
xset s off
xset s noblank
xset -dpms

# Export display env to systemd/dbus in parallel (both are IPC round-trips)
if command -v systemctl >/dev/null 2>&1; then
    systemctl --user import-environment DISPLAY XAUTHORITY &
fi
dbus-update-activation-environment --systemd DISPLAY XAUTHORITY 2>/dev/null &
wait

# ── Phase 2: Background services ───────────────────────────────────────────────


# Source theme environment so tray apps (e.g. flameshot) inherit QT_QPA_PLATFORMTHEME
# This file is generated by theme-apply.sh and updated on every theme change.
THEME_ENV="${XDG_CONFIG_HOME:-$HOME/.config}/dwm-titus/theme-env.sh"
[ -f "$THEME_ENV" ] && . "$THEME_ENV"

# Wallpaper (moved here from Phase 1 — does not need to block dwm startup)
feh --randomize --bg-fill ~/Pictures/backgrounds/* 2>/dev/null &

# Compositor
picom -b 2>/dev/null &

# Notification daemon
dunst 2>/dev/null &

# Polkit authentication agent (try common agents)
for agent in \
    /usr/lib/mate-polkit/polkit-mate-authentication-agent-1 \
    /usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 \
    /usr/libexec/polkit-gnome-authentication-agent-1 \
    /usr/lib/polkit-kde-authentication-agent-1 \
    /usr/libexec/polkit-kde-authentication-agent-1 \
    /usr/bin/lxpolkit \
    /usr/lib/lxpolkit/lxpolkit; do
    if [ -x "$agent" ]; then
        "$agent" &
        break
    fi
done

# Launch Polybar
"$HOME/.config/polybar/launch.sh" 2>/dev/null &

dex -a 2>/dev/null
