#!/usr/bin/env python3
"""Build offline application palettes from the shipped dwm presets.

These are dwm-titus palettes over GTK's built-in widget styling, not copies
of third-party theme projects. Regenerate after changing config/themes.toml.
"""
import argparse
from pathlib import Path
import tomllib

ROOT = Path(__file__).resolve().parent.parent


def luminance(color):
    channels = [int(color[i:i + 2], 16) / 255 for i in (1, 3, 5)]
    return sum(w * (c / 12.92 if c <= .04045 else ((c + .055) / 1.055) ** 2.4)
               for w, c in zip((.2126, .7152, .0722), channels))


def readable(fg, bg):
    a, b = sorted((luminance(fg), luminance(bg)))
    if (b + .05) / (a + .05) >= 4.5:
        return fg
    return '#000000' if luminance(bg) > .179 else '#ffffff'


def render(name, palette):
    bg = palette['term_bg']
    fg = readable(palette['normfgcolor'], bg)
    surface = palette['normbgcolor']
    hover = palette['selbgcolor']
    accent = palette['selbordercolor']
    selected = readable(fg, accent)
    colors = dict(bg=bg, fg=fg, surface=surface, hover=hover, accent=accent,
                  surface_fg=readable(fg, surface), hover_fg=readable(fg, hover),
                  selected=selected, border=palette['normbordercolor'])
    files = {'index.theme': f'[Desktop Entry]\nType=X-GNOME-Metatheme\nName=Dwm-{name}\n'
             f'Comment=dwm-titus {name} application palette\n\n[X-GNOME-Metatheme]\nGtkTheme=Dwm-{name}\n'}
    for version, base in [('3.0', 'Adwaita'), ('4.0', 'Default')]:
        variant = 'gtk-dark.css' if palette['dark_mode'] else ('gtk-light.css' if version == '4.0' else 'gtk.css')
        css = f'/* Generated by scripts/generate-app-themes.py. */\n@import url("resource:///org/gtk/libgtk/theme/{base}/{variant}");\n'
        css += '\n'.join(f'@define-color dwm_{key} {value};' for key, value in colors.items()) + '\n'
        css += '''@define-color theme_bg_color @dwm_bg;
@define-color theme_fg_color @dwm_fg;
@define-color theme_base_color @dwm_bg;
@define-color theme_text_color @dwm_fg;
@define-color theme_selected_bg_color @dwm_accent;
@define-color theme_selected_fg_color @dwm_selected;
window, dialog, .background, .view, textview text, treeview, list, viewport {
  background-color: @dwm_bg; color: @dwm_fg;
}
headerbar, toolbar, menubar, button, entry, spinbutton, combobox, notebook > header {
  background-image: none; background-color: @dwm_surface;
  color: @dwm_surface_fg; border-color: @dwm_border; text-shadow: none;
}
menu, .menu, popover > contents { background-color: @dwm_bg; color: @dwm_fg; }
menubar > menuitem { color: @dwm_surface_fg; }
button:hover, menuitem:hover, menubar > menuitem:hover, menu menuitem:hover,
modelbutton:hover, row:hover, treeview.view:hover {
  background-image: none; background-color: @dwm_hover; color: @dwm_hover_fg;
}
button:checked, button:active, row:selected, treeview.view:selected, iconview:selected, selection {
  background-image: none; background-color: @dwm_accent; color: @dwm_selected;
}
button:checked:hover, button:active:hover, row:selected:hover, treeview.view:selected:hover {
  background-color: @dwm_accent; color: @dwm_selected;
}
button:focus, entry:focus, row:focus { outline-color: @dwm_accent; border-color: @dwm_accent; }
button:disabled, entry:disabled, menuitem:disabled, row:disabled {
  background-image: none; background-color: @dwm_surface;
  color: @dwm_surface_fg; opacity: 0.55;
}
button label, menuitem label, modelbutton label, row label { color: inherit; }
tooltip, tooltip label { background-color: @dwm_surface; color: @dwm_surface_fg; }
'''
        files[f'gtk-{version}/gtk.css'] = css
        files[f'gtk-{version}/gtk-dark.css'] = css
    gtk2 = '# Generated by scripts/generate-app-themes.py.\nstyle "dwm-palette" {\n'
    for state, back, fore in [('NORMAL', bg, fg), ('PRELIGHT', hover, colors['hover_fg']),
                              ('ACTIVE', accent, selected), ('SELECTED', accent, selected),
                              ('INSENSITIVE', surface, colors['surface_fg'])]:
        for role, color in [('bg', back), ('base', back), ('fg', fore), ('text', fore)]:
            gtk2 += f'  {role}[{state}] = "{color}"\n'
    files['gtk-2.0/gtkrc'] = gtk2 + '}\nclass "*" style "dwm-palette"\n'
    # QPalette ColorRole order, shared by qt5ct and qt6ct.
    roles = [fg, surface, hover, surface, colors['border'], colors['border'], fg,
             selected, colors['surface_fg'], bg, bg, '#000000', accent, selected,
             accent, palette['term_color5'], surface, '#000000', surface,
             colors['surface_fg'], fg]
    qt = '[ColorScheme]\n'
    for group in ('active', 'inactive', 'disabled'):
        group_roles = roles.copy()
        if group == 'disabled':
            for index in (0, 6, 8, 20):
                group_roles[index] = palette['term_color8']
        qt += group + '_colors=' + ', '.join('#ff' + c[1:] for c in group_roles) + '\n'
    files['qt/colors.conf'] = qt
    return files


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--check', action='store_true')
    args = parser.parse_args()
    themes = tomllib.loads((ROOT / 'config/themes.toml').read_text())['theme']
    expected = {}
    for name, palette in themes.items():
        for relative, content in render(name, palette).items():
            expected[ROOT / 'assets/themes' / f'Dwm-{name}' / relative] = content
    if args.check:
        actual = {p for p in (ROOT / 'assets/themes').rglob('*') if p.is_file()}
        if actual != set(expected) or any(p.read_text() != text for p, text in expected.items()):
            raise SystemExit('Application themes are stale; run scripts/generate-app-themes.py')
    else:
        for path, text in expected.items():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(text)


if __name__ == '__main__':
    main()
