#!/bin/bash
# theme-apply.sh — Apply the active theme from themes.toml to all apps.
#
# Called automatically by DWM on config reload (SIGUSR1 / file save).
# Can also be run manually: theme-apply.sh
#
# Updates: alacritty · kitty · GTK · Qt

set -euo pipefail

# ── Locate themes.toml ────────────────────────────────────────────────────────
THEMES_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/dwm-titus/themes.toml"
if [[ ! -f "$THEMES_FILE" ]]; then
	echo "theme-apply: themes.toml not found at $THEMES_FILE" >&2
	exit 1
fi

# ── Minimal TOML section reader ───────────────────────────────────────────────
# toml_get SECTION KEY FILE — prints the value or empty string
toml_get() {
	local section="$1" key="$2" file="$3"
	awk -v sec="[$section]" -v key="$key" '
        /^\[/ { in_sec = ($0 == sec) }
        in_sec && $0 ~ "^[[:space:]]*" key "[[:space:]]*=" {
            sub(/^[^=]*=[[:space:]]*/, "")
            gsub(/"/, "")
            gsub(/[[:space:]]+#.*$/, "")  # strip inline comments (not # in hex colors)
            sub(/[[:space:]]+$/, "")
            print; exit
        }
    ' "$file"
}

# ── Read active theme name ────────────────────────────────────────────────────
THEME_NAME="$(toml_get "active" "theme" "$THEMES_FILE")"
if [[ -z "$THEME_NAME" ]]; then
	echo "theme-apply: no [active] theme set in $THEMES_FILE" >&2
	exit 1
fi

SECTION="theme.$THEME_NAME"

# ── Helper: read a value from the active theme section ───────────────────────
theme_get() {
	toml_get "$SECTION" "$1" "$THEMES_FILE"
}

# ── Read all theme values ─────────────────────────────────────────────────────
TERM_BG="$(theme_get term_bg)"
TERM_FG="$(theme_get term_fg)"
TERM_CURSOR="$(theme_get term_cursor)"
TERM_C0="$(theme_get term_color0)"
TERM_C1="$(theme_get term_color1)"
TERM_C2="$(theme_get term_color2)"
TERM_C3="$(theme_get term_color3)"
TERM_C4="$(theme_get term_color4)"
TERM_C5="$(theme_get term_color5)"
TERM_C6="$(theme_get term_color6)"
TERM_C7="$(theme_get term_color7)"
TERM_C8="$(theme_get term_color8)"
TERM_C9="$(theme_get term_color9)"
TERM_C10="$(theme_get term_color10)"
TERM_C11="$(theme_get term_color11)"
TERM_C12="$(theme_get term_color12)"
TERM_C13="$(theme_get term_color13)"
TERM_C14="$(theme_get term_color14)"
TERM_C15="$(theme_get term_color15)"

DARK_MODE="$(theme_get dark_mode)"
[[ "$DARK_MODE" != "false" ]] && DARK_MODE="true" # default to dark if unset
CURSOR_SIZE=32
if [[ "$DARK_MODE" == "true" ]]; then
	CURSOR_THEME="Capitaine-Cursors-White"
else
	CURSOR_THEME="Capitaine-Cursors"
fi

# ══════════════════════════════════════════════════════════════════════════════
# ALACRITTY — write ~/.config/alacritty/active-theme.toml
# ══════════════════════════════════════════════════════════════════════════════
ALACRITTY_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/alacritty"
if [[ -d "$ALACRITTY_DIR" ]]; then
	cat >"$ALACRITTY_DIR/active-theme.toml" <<EOF
# Auto-generated by theme-apply.sh — do not edit manually.
# Change the theme in ~/.config/dwm-titus/themes.toml instead.

[colors.primary]
background = '$TERM_BG'
foreground = '$TERM_FG'

[colors.cursor]
text   = '$TERM_BG'
cursor = '$TERM_CURSOR'

[colors.normal]
black   = '$TERM_C0'
red     = '$TERM_C1'
green   = '$TERM_C2'
yellow  = '$TERM_C3'
blue    = '$TERM_C4'
magenta = '$TERM_C5'
cyan    = '$TERM_C6'
white   = '$TERM_C7'

[colors.bright]
black   = '$TERM_C8'
red     = '$TERM_C9'
green   = '$TERM_C10'
yellow  = '$TERM_C11'
blue    = '$TERM_C12'
magenta = '$TERM_C13'
cyan    = '$TERM_C14'
white   = '$TERM_C15'
EOF

	# Ensure alacritty.toml imports active-theme.toml (add if missing)
	if [[ -f "$ALACRITTY_DIR/alacritty.toml" ]]; then
		if ! grep -q "active-theme.toml" "$ALACRITTY_DIR/alacritty.toml"; then
			# Insert active-theme.toml as first import entry
			sed -i 's|^\(import = \[\s*\)|\1\n  "~/.config/alacritty/active-theme.toml",|' \
				"$ALACRITTY_DIR/alacritty.toml"
		fi
		# Replace any existing theme import line to point to active-theme.toml
		# (removes old theme-specific imports, keeps keybinds import)
		sed -i 's|"~/.config/alacritty/[^k][^"]*\.toml"|"~/.config/alacritty/active-theme.toml"|g' \
			"$ALACRITTY_DIR/alacritty.toml"
	fi
fi

# ══════════════════════════════════════════════════════════════════════════════
# KITTY — write ~/.config/kitty/active-theme.conf
# ══════════════════════════════════════════════════════════════════════════════
KITTY_DIR="${XDG_CONFIG_HOME:-$HOME/.config}/kitty"
if [[ -d "$KITTY_DIR" ]]; then
	cat >"$KITTY_DIR/active-theme.conf" <<EOF
# Auto-generated by theme-apply.sh — do not edit manually.
# Change the theme in ~/.config/dwm-titus/themes.toml instead.

background  $TERM_BG
foreground  $TERM_FG
cursor      $TERM_CURSOR

color0  $TERM_C0
color1  $TERM_C1
color2  $TERM_C2
color3  $TERM_C3
color4  $TERM_C4
color5  $TERM_C5
color6  $TERM_C6
color7  $TERM_C7
color8  $TERM_C8
color9  $TERM_C9
color10 $TERM_C10
color11 $TERM_C11
color12 $TERM_C12
color13 $TERM_C13
color14 $TERM_C14
color15 $TERM_C15
EOF

	# Ensure kitty.conf has 'include active-theme.conf' at the top
	if [[ -f "$KITTY_DIR/kitty.conf" ]]; then
		if ! grep -q "include active-theme.conf" "$KITTY_DIR/kitty.conf"; then
			sed -i '1s|^|include active-theme.conf\n|' "$KITTY_DIR/kitty.conf"
		fi
	fi

	# Signal kitty to reload (no restart needed)
	if command -v kitty &>/dev/null; then
		kill -SIGUSR1 "$(pgrep -x kitty)" 2>/dev/null || true
	fi
fi

# ══════════════════════════════════════════════════════════════════════════════
# GTK DARK / LIGHT MODE
# ══════════════════════════════════════════════════════════════════════════════
if [[ "$DARK_MODE" == "true" ]]; then
	GTK_COLOR_SCHEME="prefer-dark"
	GTK_THEME_NAME="Adwaita-dark"
	GTK_DARK_PREF=1
else
	GTK_COLOR_SCHEME="default"
	GTK_THEME_NAME="Adwaita"
	GTK_DARK_PREF=0
fi

# Helper: set or add a key in a [Settings] ini file without destroying other settings
gtk_ini_set() {
	local file="$1" key="$2" value="$3"
	mkdir -p "$(dirname "$file")"
	if [[ ! -f "$file" ]]; then
		printf '[Settings]\n%s=%s\n' "$key" "$value" >"$file"
		return
	fi
	if grep -q "^${key}" "$file"; then
		sed -i "s|^${key}=.*|${key}=${value}|" "$file"
	elif grep -q '^\[Settings\]' "$file"; then
		sed -i "/^\[Settings\]/a ${key}=${value}" "$file"
	else
		printf '\n[Settings]\n%s=%s\n' "$key" "$value" >>"$file"
	fi
}

# GTK3
gtk_ini_set "${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/settings.ini" \
	"gtk-application-prefer-dark-theme" "$GTK_DARK_PREF"
gtk_ini_set "${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/settings.ini" \
	"gtk-theme-name" "$GTK_THEME_NAME"
gtk_ini_set "${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/settings.ini" \
	"gtk-cursor-theme-name" "$CURSOR_THEME"
gtk_ini_set "${XDG_CONFIG_HOME:-$HOME/.config}/gtk-3.0/settings.ini" \
	"gtk-cursor-theme-size" "$CURSOR_SIZE"

# GTK4
gtk_ini_set "${XDG_CONFIG_HOME:-$HOME/.config}/gtk-4.0/settings.ini" \
	"gtk-application-prefer-dark-theme" "$GTK_DARK_PREF"
gtk_ini_set "${XDG_CONFIG_HOME:-$HOME/.config}/gtk-4.0/settings.ini" \
	"gtk-theme-name" "$GTK_THEME_NAME"
gtk_ini_set "${XDG_CONFIG_HOME:-$HOME/.config}/gtk-4.0/settings.ini" \
	"gtk-cursor-theme-name" "$CURSOR_THEME"
gtk_ini_set "${XDG_CONFIG_HOME:-$HOME/.config}/gtk-4.0/settings.ini" \
	"gtk-cursor-theme-size" "$CURSOR_SIZE"

# GTK2
printf 'gtk-theme-name="%s"\ngtk-cursor-theme-name="%s"\ngtk-cursor-theme-size=%s\n' \
	"$GTK_THEME_NAME" "$CURSOR_THEME" "$CURSOR_SIZE" >"$HOME/.gtkrc-2.0"

# Xcursor settings for Xlib applications and programs launched after reload.
CURSOR_XRESOURCES="${XDG_CONFIG_HOME:-$HOME/.config}/dwm-titus/cursor.Xresources"
printf 'Xcursor.theme: %s\nXcursor.size: %s\n' \
	"$CURSOR_THEME" "$CURSOR_SIZE" >"$CURSOR_XRESOURCES"
if command -v xrdb &>/dev/null && [[ -n "${DISPLAY:-}" ]]; then
	xrdb -merge "$CURSOR_XRESOURCES"
fi

# Live D-Bus update — affects running GTK4 apps, Flatpaks, and XDG portals
if command -v gsettings &>/dev/null; then
	gsettings set org.gnome.desktop.interface color-scheme "$GTK_COLOR_SCHEME" 2>/dev/null || true
	gsettings set org.gnome.desktop.interface gtk-theme "$GTK_THEME_NAME" 2>/dev/null || true
	gsettings set org.gnome.desktop.interface cursor-theme "$CURSOR_THEME" 2>/dev/null || true
	gsettings set org.gnome.desktop.interface cursor-size "$CURSOR_SIZE" 2>/dev/null || true
fi

# ══════════════════════════════════════════════════════════════════════════════
# QT DARK / LIGHT MODE
# ══════════════════════════════════════════════════════════════════════════════
# Prefer qt6ct > qt5ct; fall back to gtk3 (inherits GTK theme set above)
if command -v qt6ct &>/dev/null; then
	QT_PLATFORM_THEME="qt6ct"
elif command -v qt5ct &>/dev/null; then
	QT_PLATFORM_THEME="qt5ct"
else
	QT_PLATFORM_THEME="gtk3"
fi

# Write persistent env file — sourced by autostart.sh so tray apps inherit it
THEME_ENV_FILE="${XDG_CONFIG_HOME:-$HOME/.config}/dwm-titus/theme-env.sh"
cat >"$THEME_ENV_FILE" <<EOF
# Auto-generated by theme-apply.sh — do not edit manually.
export QT_QPA_PLATFORMTHEME=$QT_PLATFORM_THEME
export XCURSOR_THEME=$CURSOR_THEME
export XCURSOR_SIZE=$CURSOR_SIZE
EOF

# Update qt5ct / qt6ct color scheme config if that tool is the active theme
if [[ "$QT_PLATFORM_THEME" == "qt5ct" || "$QT_PLATFORM_THEME" == "qt6ct" ]]; then
	QT_CT_CONF="${XDG_CONFIG_HOME:-$HOME/.config}/${QT_PLATFORM_THEME}/${QT_PLATFORM_THEME}.conf"
	if [[ -f "$QT_CT_CONF" ]]; then
		if [[ "$DARK_MODE" == "true" ]]; then
			QT_CT_SCHEME="/usr/share/${QT_PLATFORM_THEME}/colors/darker.conf"
		else
			QT_CT_SCHEME=""
		fi
		if grep -q '^color_scheme_path' "$QT_CT_CONF"; then
			sed -i "s|^color_scheme_path=.*|color_scheme_path=$QT_CT_SCHEME|" "$QT_CT_CONF"
		else
			sed -i "/^\[Appearance\]/a color_scheme_path=${QT_CT_SCHEME}" "$QT_CT_CONF"
		fi
	fi
fi

# Propagate to user services and D-Bus-activated services in this session
if command -v systemctl &>/dev/null; then
	systemctl --user import-environment \
		QT_QPA_PLATFORMTHEME \
		XCURSOR_THEME \
		XCURSOR_SIZE 2>/dev/null || true
fi
if command -v dbus-update-activation-environment &>/dev/null; then
	dbus-update-activation-environment --systemd \
		QT_QPA_PLATFORMTHEME="$QT_PLATFORM_THEME" \
		XCURSOR_THEME="$CURSOR_THEME" \
		XCURSOR_SIZE="$CURSOR_SIZE" 2>/dev/null || true
fi

# Restart flameshot so its tray icon picks up the new theme
if pgrep -x flameshot &>/dev/null; then
	pkill -x flameshot 2>/dev/null || true
	sleep 0.3
	QT_QPA_PLATFORMTHEME="$QT_PLATFORM_THEME" flameshot &
fi

echo "theme-apply: applied theme '$THEME_NAME'"
