#!/bin/bash
# ─────────────────────────────────────────────────────────
# xscreensaver-setup.sh — Install and configure xscreensaver
# Uses Fedora's package manager, installs xscreensaver, writes
# a sensible default config, and sets it up to start on login.
# ─────────────────────────────────────────────────────────
set -euo pipefail

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

info() { echo -e "  ${CYAN}[INFO]${NC} $1"; }
pass() { echo -e "  ${GREEN}[ OK ]${NC} $1"; }
warn() { echo -e "  ${YELLOW}[WARN]${NC} $1"; }
fail() {
	echo -e "  ${RED}[FAIL]${NC} $1"
	exit 1
}
header() { echo -e "\n${BOLD}=== $1 ===${NC}"; }

DISTRO_ID=unknown
OS_RELEASE_FILE=/etc/os-release
if [[ ${DWM_TEST_MODE:-0} == 1 && -n ${DWM_OS_RELEASE:-} ]]; then
	OS_RELEASE_FILE=$DWM_OS_RELEASE
fi
if [[ -r $OS_RELEASE_FILE ]]; then
	# shellcheck disable=SC1090
	source "$OS_RELEASE_FILE"
	DISTRO_ID=${ID:-unknown}
fi
[[ $DISTRO_ID == fedora ]] || fail "dwm-titus supports Fedora only."

# ── Detect package manager and install ───────────────────
header "Installing xscreensaver"

install_pkg() {
	command -v dnf >/dev/null 2>&1 || fail "dnf is required; dwm-titus supports Fedora only."
	info "Installing with dnf"
	sudo dnf install -y xscreensaver
}

if command -v xscreensaver &>/dev/null; then
	pass "xscreensaver is already installed"
else
	install_pkg
	if command -v xscreensaver &>/dev/null; then
		pass "xscreensaver installed successfully"
	else
		fail "xscreensaver installation failed"
	fi
fi

# ── Write default configuration ──────────────────────────
header "Configuring xscreensaver"

XSCREENSAVER_CONFIG="$HOME/.xscreensaver"

if [[ -f "$XSCREENSAVER_CONFIG" ]]; then
	warn "Existing config found at $XSCREENSAVER_CONFIG — backing up to ${XSCREENSAVER_CONFIG}.bak"
	cp "$XSCREENSAVER_CONFIG" "${XSCREENSAVER_CONFIG}.bak"
fi

cat >"$XSCREENSAVER_CONFIG" <<'EOF'
# XScreenSaver configuration — generated by dwm-titus xscreensaver-setup.sh

mode:         blank
timeout:      0:10:00
cycle:        0:10:00
lock:         False
lockTimeout:  0:00:00
dpmsEnabled:  False
dpmsStandby:  0:00:00
dpmsSuspend:  0:00:00
dpmsOff:      0:00:00
fade:         True
fadeSeconds:  0:00:03
unfade:       True
splash:       False
nice:         10
EOF

pass "Config written to $XSCREENSAVER_CONFIG"

# ── Set up autostart ─────────────────────────────────────
header "Setting up autostart"

AUTOSTART_DIR="$HOME/.config/autostart"
DESKTOP_FILE="$AUTOSTART_DIR/xscreensaver.desktop"

mkdir -p "$AUTOSTART_DIR"

cat >"$DESKTOP_FILE" <<'EOF'
[Desktop Entry]
Type=Application
Name=XScreenSaver
Comment=Start XScreenSaver daemon
Exec=xscreensaver --no-splash
Hidden=false
X-GNOME-Autostart-enabled=true
EOF

pass "XDG autostart entry created at $DESKTOP_FILE"

# Also start the daemon now if it's not already running
if pgrep -x xscreensaver &>/dev/null; then
	pass "xscreensaver daemon is already running"
else
	info "Starting xscreensaver daemon…"
	xscreensaver --no-splash &
	disown
	pass "xscreensaver daemon started"
fi

# ── Summary ──────────────────────────────────────────────
header "Done"
echo ""
info "xscreensaver is installed and will start on login."
info "Screen will blank after 10 minutes (locking is disabled)."
info "DPMS is disabled (nvidia wake-up workaround)."
info "Run 'xscreensaver-settings' to customize further."
echo ""
