name: Deploy Docs to Pages

on:
  push:
    branches:
      - main
    paths:
      - "docs/**"
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    if: github.repository == 'ChrisTitusTech/dwm-titus'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Install mdbook
        uses: peaceiris/actions-mdbook@v2
        with:
          mdbook-version: "latest"
      - name: Install mdbook preprocessors
        run: cargo install mdbook-last-changed mdbook-toc
      - name: Build with mdbook
        run: mdbook build docs
      - name: Setup Pages
        uses: actions/configure-pages@v5
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./docs/book

  deploy:
    if: github.repository == 'ChrisTitusTech/dwm-titus'
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
